import { graph } from "./graph";
import type { GraphState } from "./types";
import type { InvestmentReport } from "@/types";

export { graph } from "./graph";
export * from "./state";
export * from "./types";

/**
 * Runs the LangGraph investment intelligence agent.
 * Executes the compiled graph from the initial state through all nodes.
 *
 * @param companyName Name of the company to research and analyze
 * @returns Structured InvestmentReport generated by the pipeline
 */
export async function runInvestmentAgent(companyName: string): Promise<InvestmentReport> {
  const initialState: Partial<GraphState> = {
    companyName,
    errors: [],
  };

  // Execute the graph pipeline
  const finalState = await graph.invoke(initialState);

  // Check for any errors recorded during execution
  if (finalState.errors && finalState.errors.length > 0) {
    throw new Error(finalState.errors.join("; "));
  }

  if (!finalState.report) {
    throw new Error("Graph pipeline execution completed but no report was formatted.");
  }

  return finalState.report;
}
