import { graph } from "./graph";
import type { GraphState } from "./types";
import type { InvestmentReport } from "@/types";
import { validateEnv } from "@/lib/env-validator";

export { graph } from "./graph";
export * from "./state";
export * from "./types";

interface ReportCacheEntry {
  report: InvestmentReport;
  timestamp: number;
}

// Global in-memory final report cache map (15 minutes TTL)
export const finalReportCache = new Map<string, ReportCacheEntry>();
const CACHE_TTL = 15 * 60 * 1000;

/**
 * Runs the LangGraph investment intelligence agent.
 * Executes the compiled graph from the initial state through all nodes.
 *
 * @param companyName Name of the company to research and analyze
 * @returns Structured InvestmentReport generated by the pipeline
 */
export async function runInvestmentAgent(companyName: string): Promise<InvestmentReport> {
  validateEnv();
  
  const key = companyName.trim().toLowerCase();
  
  // Check final report cache
  const cached = finalReportCache.get(key);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    console.log(`[Cache] Report reused for ${companyName}`);
    return cached.report;
  }

  const startTime = Date.now();
  console.log("[LangGraph] Starting graph execution...");

  const initialState: Partial<GraphState> = {
    companyName,
    errors: [],
  };

  // Execute the graph pipeline
  const finalState = await graph.invoke(initialState);

  const duration = Date.now() - startTime;
  console.log(`[PerformanceMetrics] Total Graph Execution Time: ${duration}ms`);
  console.log("[LangGraph] Graph execution complete.");

  // Check for any errors recorded during execution
  if (finalState.errors && finalState.errors.length > 0) {
    throw new Error(finalState.errors.join("; "));
  }

  if (!finalState.report) {
    throw new Error("Graph pipeline execution completed but no report was formatted.");
  }

  // Save to cache
  finalReportCache.set(key, { report: finalState.report, timestamp: Date.now() });

  return finalState.report;
}
